env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
