env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules:
  {
    "import/no-extraneous-dependencies": off,
    "vue/multi-word-component-names": off,
  }
