env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
  - "@typescript-eslint"
rules:
  {
    "import/no-extraneous-dependencies":
      [
        "error",
        {
          "devDependencies":
            [
              "**/*.stories.*",
              "**/.storybook/**/*.*",
              "vite-env.d.ts",
              "vite.config.ts",
            ],
        },
      ],
  }
